version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: mydata
    volumes:
      - ./backend:/app
    ports:
      - 8082:8080
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydata
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
